[package]
name = "websocket-channels"
version = "0.6.0"
edition = "2021"
license = "MIT"
description = "Websocket channels compatible with Phixnix"
repository = ""
keywords = ["axum", "axum-ws", "websocket", "channels"]

[[bin]]
name = "axum-server"
path = "src/bin/axum-server.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.23.0" }

tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.0", features = ["fs", "trace"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

axum = { version = "0.7.5", features = ["default", "ws"] }
axum-extra = { version = "0.9.3" }
futures = "0.3.30"
# futures-util = { version = "0.3.30"}

serde = "1.0.203"
serde_tuple = "0.5.0"
serde_json = "1.0.117"
uuid = { version = "1.8.0", features = ["v4"] }

chrono = "0.4.38"

hex = "0.4.3"

