[package]
name = "channels"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Websocket channels compatible with Phixnix"
repository = "https://github.com/emctoo/websocket-channels"
keywords = ["axum", "axum-ws", "warp", "websocket", "channels"]

[[bin]]
name = "channel-axum"
path = "src/bin/axum-server.rs"

[[bin]]
name = "channel-warp"
path = "src/bin/warp-server.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.26" }
tokio-stream = "0.1"

tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["fs", "trace"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

futures = "0.3"
# futures-util = { version = "0.3.30"}

axum = { version = "0.7.5", features = ["default", "ws"] }
axum-extra = { version = "0.9.3" }

warp = { version = "0.3", features = ["default"] }

serde = "1.0"
serde_tuple = "1.1"
serde_json = "1.0"
uuid = { version = "1.8.0", features = ["v4"] }

chrono = "*"

# hex = "0.4.3"
redis = { version = "0.27", features = ["tokio-comp"] }

clap = { version = "4.5", features = ["color", "derive", "wrap_help"] }
dotenv = { version = "0.15" }
jsonwebtoken = { version = "9.3" }
rand = { version = "0.8" }
