name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - "container/**"
  pull_request:
    paths:
      - "container/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: channel

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release version
        id: release
        run: |
          RESPONSE=$(curl -s https://api.github.com/repos/emctoo/channel/releases/latest)
          LATEST_VERSION=$(echo $RESPONSE | jq -r .tag_name)

          echo "version=${LATEST_VERSION}" >> $GITHUB_OUTPUT
          echo "Found version: ${LATEST_VERSION}"

      - name: Set Docker tags
        id: meta
        run: |
          VERSION="${{ steps.release.outputs.version }}"
          TAGS="${REGISTRY}/${OWNER}/${IMAGE_NAME}:latest"

          if [ -n "$VERSION" ]; then
            TAGS="${TAGS},${REGISTRY}/${OWNER}/${IMAGE_NAME}:${VERSION}"
          fi

          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "Using tags: ${TAGS}"

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/container
          file: ${{ github.workspace }}/container/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          build-args: |
            VERSION=${{ steps.release.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
